{{- range $key, $value := .Values.backup.storages }}
{{- if and (hasKey $value "type") (eq $value.type "s3") (hasKey $value "credentialsAccessKey") (hasKey $value "credentialsSecretKey") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pxc-database.fullname" $ }}-s3-{{ $key }}
  labels:
{{ include "pxc-database.labels" $ | indent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ $value.credentialsAccessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ $value.credentialsSecretKey | b64enc }}
{{- end }}
{{- end }}
